#!/usr/bin/env sh

user=$(whoami)

if [ "${user}" != "root" ]; then
	printf "Please run this program as root!\n"
	exit 1
fi

pacman -Syu --needed --noconfirm \
	base-devel \
	bbswitch \
	blueman \
	bluez \
	bumblebee \
	docker \
	docker-compose \
	git \
	go \
	grim \
	hub \
	jdk11-openjdk \
	mako \
	maven \
	openssh \
	pavucontrol \
	pulseaudio \
	pulseaudio-bluetooth \
	python-pip \
	python-virtualenv \
	rofi \
	slurp \
	stow \
	sudo \
	sway \
	swayidle \
	swaylock \
	task \
	termite \
	ttf-font-awesome \
	ttf-inconsolata \
	vim \
	waybar \
	xorg-server-xwayland \
	zsh

curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

pip install taskw