#!/usr/bin/env sh

user=$(whoami)

if [ "${user}" != "root" ]; then
	printf "Please run this program as root!\n"
	exit 1
fi

pacman -Syu --needed --noconfirm \
	base-devel \
	bbswitch \
	bumblebee \
	docker \
	docker-compose \
	git \
	go \
	grim \
	jdk11-openjdk \
	maven \
	python-pip \
	python-virtualenv \
	rofi \
	slurp \
	stow \
	sudo \
	sway \
	swayidle \
	swaylock \
	task \
	ttf-font-awesome \
	ttf-inconsolata \
	vim \
	xorg-server-xwayland \
	zsh