#!/usr/bin/env sh

user=$(whoami)

if [ "${user}" != "root" ]; then
	printf "Please run this program as root!\n"
	exit 1
fi

pacman -Syu --needed \
	base-devel \
	bbswitch \
	bumblebee \
	firefox \
	git \
	go \
	jdk11-openjdk \
	python-pip \
	python-virtualenv \
	rofi \
	stow \
	sudo \
	sway \
	ttf-font-awesome \
	ttf-inconsolata \
	vim \
	xorg-server-xwayland \
	zsh